### ISSUE TITLE
Downloading Java JRE... Failed to download Java JRE. Reason: 0x38 "OpenSSL SSL_read: Connection was reset, errno 10054".

### ISSUE THREAD

**Issue by RichardsATcn** [SlimeVR/SlimeVR-Installer#19]
Downloading Java JRE...
Failed to download Java JRE. Reason: 0x38 "OpenSSL SSL_read: Connection was reset, errno 10054".

**Comment by deiteris** [comment]
Are you able to access this URL? Looks like the problem with your internet connection
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12%2B7/OpenJDK11U-jre_x64_windows_hotspot_11.0.12_7.zip

**Comment by loucass003** [comment]
it has been a 10 months and no other occurence of this. Should we close it ?

**Comment by unlogisch04** [comment]
I agree on closing this issue
