### ISSUE TITLE
Documentation URL leads to a 404

### ISSUE THREAD

**Issue by hyblocker** [SlimeVR/SlimeVR-Installer#21]
After the installer installs SlimeVR, and checking the "Open Documentation" option, the page opened leads to a 404.

The URL opened: [https://docs.slimevr.dev/slimevr-setup.html](https://docs.slimevr.dev/slimevr-setup.html)

**Comment by adigyran** [comment]
#20

**Comment by Eirenliel** [comment]
Replaced the release file, sorry, forgot about it
