### ISSUE TITLE
Redundant Installation of JRE

### ISSUE THREAD

**Issue by BakaJzon** [SlimeVR/SlimeVR-Installer#26]
I had already installed Eclipse Temurin 11 for x64,  added java to path,  and successfully run 'java' in terminal. But when I start the installer, it still install openjdk jre again. I wander what happened.

And for some [Network problem](https://en.wikipedia.org/wiki/Great_Firewall), I may need proxy tools to download it. Can installer use System Proxy Configuration?

**Comment by Eirenliel** [comment]
This is not redundant, it makes sure that the JRE installed is supported and compatible and doesn't require people to install it themselves, not leaves traces in the system.

On the proxy, @deiteris might know.

**Comment by deiteris** [comment]
I'm afraid no. Installer uses cURL to download the data, but it doesn't use System Proxy by default. We probably could add a command line arguments that would allow you to specify your proxy configuration.

**Comment by BakaJzon** [comment]
Thanks a lot!
