### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by JJoshyyy** [SlimeVR/SlimeVR-Installer#38]
this error:
Output folder: C:\Program Files (x86)\SlimeVR Server
Downloading SlimeVR Server...
Failed to download SlimeVR Server. Reason: 0x6 "Could not resolve host: github.com".

**Comment by JoshyJoshyJoshy** [comment]
could it be my school internet blocking a link?

**Comment by Eirenliel** [comment]
Yes.

**Comment by JoshyJoshyJoshy** [comment]
Thats fun. now its this
Output folder: C:\Program Files (x86)\SlimeVR Server
Downloading SlimeVR Server...
Failed to download SlimeVR Server. Reason: 0x3c "SSL certificate problem: self signed certificate in certificate chain".

**Comment by JoshyJoshyJoshy** [comment]
> Yes.

Even then, github itself is unblocked

**Comment by Louka3000** [comment]
@JoshyJoshyJoshy Can you join our Discord for tech support instead of using Github issues
https://discord.com/invite/slimevr
Check #technical-support or #support-forum

**Comment by JoshyJoshyJoshy** [comment]
Alright, it will take me like an hour or 2, im at school at the moment lol

**Comment by JoshyJoshyJoshy** [comment]
> @JoshyJoshyJoshy Can you join our Discord for tech support instead of using Github issues https://discord.com/invite/slimevr Check #technical-support or #support-forum We can tell you how to manually install SlimeVR without the installer if nothing works.

Ah, ok. I believe it is my school's wifi blocking tthe connection
