### ISSUE TITLE
cant trust the file on windows

### ISSUE THREAD

**Issue by cuppuppy10** [SlimeVR/SlimeVR-Installer#40]
all it says when i try and download it is "slimevr_web_installer.exe isn't commonly downloaded. make sure you trust slimevr_web_installer.exe before you..." the rest it won't show me but I don't know how to trust the file, and no one will help me

**Comment by ButterscotchV** [comment]
Assuming this is with Microsoft Edge, you press the 3 dots and press the "Keep" button.
![image](https://user-images.githubusercontent.com/5095026/207463974-a8c5f4d1-6a1f-4c24-ae8d-bfd6ff14929e.png)
