### ISSUE TITLE
Failed to download SlimeVR Server

### ISSUE THREAD

**Issue by WavesMan** [SlimeVR/SlimeVR-Installer#47]
![872482b392da507e669ed930e5dcbc4c](https://github.com/SlimeVR/SlimeVR-Installer/assets/104572398/4142ea96-0fcb-4bbd-b36e-e5b988c5c5f0)

**Comment by unlogisch04** [comment]
Works for me. The GitHub Certificate is valid and was not changed in this days. Seems to be on your side (check your System Date, Firewall, Antivirus). 
It try to download following file in that step:
<https://github.com/SlimeVR/SlimeVR-Server/releases/latest/download/SlimeVR-win64.zip>
