### ISSUE TITLE
Failed to download SlimeVR Server. Reason: 0x3c "SSL certificate problem: unable to get local issuer certificate".

### ISSUE THREAD

**Issue by doudou0547** [SlimeVR/SlimeVR-Installer#48]
Output folder: D:\SlimeVR Server
Downloading SlimeVR Server...
Failed to download SlimeVR Server. Reason: 0x3c "SSL certificate problem: unable to get local issuer certificate".

**Comment by Pixelhashu** [comment]
Do you have a discord? from seeing the 3 issues you posted one after another this is less of an installer issue and a your pc's network issue.

**Comment by ButterscotchV** [comment]
Please don't open multiple issues for the same thing, this looks like an issue with your networking, not the installer.
